const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');
const forge = require('node-forge');
const fs = require('fs');
const path = require('path');
const signatureEngine = require('../server/utils/signature_engine');

/**
 * Integration test for Phase 5-2: PAdES Baseline Signing.
 * Generates a mock PDF and certificate, then signs it.
 */
async function runTest() {
    console.log('--- Testing PDF Digital Signing ---');
    
    const certPath = path.resolve('cert.p12');
    const pdfPath = path.resolve('test_unsigned.pdf');
    const signedPdfPath = path.resolve('test_signed.pdf');
    const password = 'test-password';

    // 1. Generate Mock P12
    console.log('1. Preparing mock environment...');
    const keys = forge.pki.rsa.generateKeyPair(2048);
    const cert = forge.pki.createCertificate();
    cert.publicKey = keys.publicKey;
    cert.serialNumber = '01';
    cert.validity.notBefore = new Date();
    cert.validity.notAfter = new Date();
    cert.validity.notAfter.setFullYear(cert.validity.notBefore.getFullYear() + 1);
    const attrs = [{ name: 'commonName', value: 'DoVER Digital Authority' }];
    cert.setSubject(attrs);
    cert.setIssuer(attrs);
    cert.sign(keys.privateKey, forge.md.sha256.create());
    const p12Asn1 = forge.pkcs12.toPkcs12Asn1(keys.privateKey, cert, password);
    const p12Buffer = Buffer.from(forge.asn1.toDer(p12Asn1).getBytes(), 'binary');
    fs.writeFileSync(certPath, p12Buffer);

    process.env.SIGNING_P12_PASSWORD = password;

    // 2. Create Dummy PDF
    console.log('2. Creating sample PDF...');
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([600, 400]);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    page.drawText('OFFICIAL DOCUMENT RECORD', { x: 50, y: 350, size: 20, font, color: rgb(0, 0, 0) });
    page.drawText('This is a test document generated by DoVER.', { x: 50, y: 320, size: 12, font });
    page.drawText('Verification ID: TEST-12345', { x: 50, y: 300, size: 10, font });
    const unsignedBuffer = await pdfDoc.save();
    fs.writeFileSync(pdfPath, unsignedBuffer);

    // 3. Sign PDF
    console.log('3. Running SignatureEngine.signPdf()...');
    const signedBuffer = await signatureEngine.signPdf(unsignedBuffer, {
        reason: 'Authorized Test Signature',
        location: 'Mumbai, IN'
    });

    // 4. Validate Result
    if (signedBuffer && signedBuffer.length > unsignedBuffer.length) {
        fs.writeFileSync(signedPdfPath, signedBuffer);
        console.log('\n✅ Signing Test: PASSED');
        console.log(`   - Unsigned Size: ${unsignedBuffer.length} bytes`);
        console.log(`   - Signed Size: ${signedBuffer.length} bytes`);
        console.log(`   - File saved to: ${signedPdfPath}`);
    } else {
        console.error('\n❌ Signing Test: FAILED');
        process.exit(1);
    }

    // Cleanup
    if (fs.existsSync(certPath)) fs.unlinkSync(certPath);
    if (fs.existsSync(pdfPath)) fs.unlinkSync(pdfPath);
    // Keep test_signed.pdf for manual inspection
    process.exit(0);
}

runTest().catch(err => {
    console.error('Fatal Signing Error:', err);
    process.exit(1);
});
